name: pcdarts-tf2
channels:
  - conda-forge

dependencies:
  - python==3.7
  - pip
  - pip:
    - tensorflow-gpu
    - tensorflow_datasets
    - numpy
    - opencv-python
    - PyYAML
    - ipython
    - python-graphviz
